### ISSUE TITLE
Fivestar Rating field widget types

### ISSUE THREAD

**Issue by victorcpereira** [pedrorocha-net/fivestar#3]
Create class FiveStartWidgetBase extends WidgetBase
This class will be the base to the fivestar widgets.

Then implements the following widgets:  
- Stars (rated while editing)
- Stars (rated while viewing)
- Select list (rated while editing)

_Reference: https://www.drupal.org/node/2128865_
Related #2

**Comment by pedrorocha-net** [comment]
I think it makes sense to have only one widget for "rated while editing/viewing" and have a new option on the field settings. I think it'll become better organised this way.

"Select list" should be a different widget, indeed, as it'll not make use of big part of the code for stars handling.

**Comment by victorcpereira** [comment]
Created two widgets: "Stars" and "Select list"
Now the "rated while viewing/editing" is a field setting.
